# Generated by Django 4.1.5 on 2023-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('date', models.CharField(max_length=100, verbose_name='Date')),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'OHLC',
                'verbose_name_plural': 'OHLC Data ',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OrdersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=10, verbose_name='User')),
                ('Time', models.CharField(max_length=15, verbose_name='Time')),
                ('order', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders ',
                'ordering': ['Time'],
            },
        ),
    ]
